/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider.component";
import { FlashProvider } from "@/components/Flash.component";
import { DrawerWrapper } from "../context/DrawerContext";
import { DrawerComponent } from "@/components/drawer.component";
import { UserWrapper } from "@/context/UserContext";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserWrapper>
          <DrawerWrapper>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >
              <FlashProvider>
                <Suspense fallback={<div>Loading ...</div>}>
                  {children}
                </Suspense>
                <DrawerComponent />
              </FlashProvider>
            </ThemeProvider>
          </DrawerWrapper>
        </UserWrapper>
      </body>
    </html>
  );
}
